<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
	<head>
		<link rel="stylesheet" href="../css/style.css" />
		<link rel="stylesheet" href="../css/bootstrap.css" />
		<link rel="stylesheet" type="text/css" href="../js/zoombox/zoombox.css" /><link rel="stylesheet" type="text/css" href="http://grafikart.fr/css/zoombox.css" /> 
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
		<link rel="stylesheet" href="../css/stylesheet.css" type="text/css" charset="utf-8" />
	</head>

	<div class="interview" >
		<div id="scriptum-text">
			<h3 id="titleIntw">Fantasmas ocultos y otros demonios - entrevista con Ghost</h3></br>
			<img src="../img/scriptum/fantasmas_ocultos.jpg"/></br></br>
			
			<p id="iw_question"> La banda sueca de rock/doom oculto Ghost es una de las más rápidas estrellas en ascenso en el firmamento del metal. Recientemente, la banda lanzó Infestissumam, un disco que, sin duda, consolidará aún más la reputación del <b>Papa Emeritus II</b> y sus <b>Ghouls</b> sin nombre. En nombre de <b>Ghost Cult</b>, Marcus J. West tuvo una pequeña charla con uno de los Ghouls sin nombre justo antes de que la banda entrara al escenario …</br></br>Este paquete de gira con The Defiled, Gojira y Ghost es muy interesante. ¿Cuáles son sus pensamientos?</p>
			
			<p id="iw_answer"> Creo que este paquete trabaja en nuestro favor. Gojira es una banda muy interesante, así como The Defiled. Sin embargo, no puedo decir mucho acerca de las bandas que están abriendo para nosotros debido a la naturaleza de lo que hacemos en el escenario, nunca tenemos tiempo para ver otros shows, tenemos que prepararnos, hacer un montón de cosas. Nos destacamos cuando estamos rodeados de bandas que no suenan como nosotros como en esta gira. ¿Por qué deberíamos tocar junto a grupos que suenan similar a lo que hacemos? Haría que nosotros y ellos nos viéramos peor. Quiero decir, hay muchos de nuestros fans que sigue diciendo que deberíamos hacer una gira con King Diamond. No, no se debe! Eso lo haría ver viejo y nos haría ver como si lo estuviéramos copiando. Esa es una idea muy mala! La forma en que somos percibidos por muchos, es que somos el resultado de una mezcla de <i>King Diamond, Kiss y Alice Cooper</i>. Así que imagínate si tocáramos con todos ellos. Nos haría ver como un grupo de payasos. Si optamos por tocar con bandas como estas,  no vamos a ninguna parte. Hay tantas bandas, en especial de donde somos,  que están tan encerradas en tocar ese tipo de festivales “nicho”, donde todas las bandas suenan más o menos lo mismo. Los fanáticos que acuden a estas fiestas quieren tener una dosis completa de ese tipo de música, sabemos de dónde vienen el heavy metal y el doom, pero no somos una banda de heavy metal, no somos una banda de doom. Estamos tratando de hacer algo que es diferente, no estamos tratando de ser una banda de escena, estamos tratando de ser  teatro. Ghost no está diciendo a sus seguidores cómo vestirse o cómo pensar, sólo queremos que vengan a nuestros conciertos y escapen por un tiempo, es escapismo.</p>
			
			<p id="iw_question"> Una de las características más llamativas de <b>Ghost</b> es su ropa elaborada y todo el secreto que rodea a la banda. ¿Qué pasa con eso?</p>
			
			<p id="iw_answer"> En un aspecto, creo que protejemos a nuestros fans de saber quiénes somos. Hay muchos aspectos que intervienen en la consideración cuando su subconsciente elige gustar de alguien, tantas cosas que contaminan la línea de la forma del arte para el receptor, esta es tristemente la naturaleza de la manera en que la humanidad percibe la música. Es mucho más basado en lo que se oye, cuándo y en qué estado de ánimo uno se encuentra. Si le espera un viaje de dos horas en coche cuando usted se siente infeliz, cualquier música que se oye durante esas dos horas puede cambiar ya sea su visión de  la música o de todo el viaje. Es la dura y brutal realidad de los creadores de música. Piense en el grupo <i>Swedish House Mafia</i>, que es exactamente por qué se hizo tan enorme: la gente sale los viernes, esperando una muy buena noche, se escuchan sus canciones que acompañan la sensación de “con la esperanza de encontrar al que es” o “tener el mejor tiempo de sus vidas ”. Este es sin duda uno de los aspectos que queremos quitar de Ghost, ya que cualquier otra banda tiene tanto interés por envolver su arte con su galería personal, como su lugar de origen, esto es lo que comen, esto es una foto de su perro. Están tan desesperados, me pregunto si realmente quieren tener éxito en lo que están haciendo o si lo que quieren es ser famosos. Eso también estropea la forma en que usted percibe una carrera que se muestra al público. Piense en Kim Kardashian por ejemplo, sólo es conocida por ser conocida. Ella es básicamente lo contrario de un artista, ella es sólo conocida. Quiero decir que ella se clavó en la cinta, pero si le preguntas a cualquier persona por qué es conocida, nadie lo sabe. Ella es una celebridad, ella está justo en el lado opuesto de los artistas súper eclécticos, principalmente escritores, que nadie sabe quiénes son, que sólo se conocen únicamente por su arte. En el medio hay una gran cantidad de arte dando vueltas y mucho se contamina, por lo que queríamos cambiar esto un poco. Queremos que las personas se enfoquen en lo que estamos haciendo con nuestra música y en nuestros shows. Desde un punto de vista personal, quiero llenar los vacíos que yo quería ver: tenemos Ghost, hagamos eso en esto y esperemos que a la gente le guste. Pero a para hacer eso, tuvimos que permanecer en el anonimato porque no quiero ni que seamos personas reales, excepto Papa, obviamente, ya que es el tipo.</p>
			
			<p id="iw_question"> Opus Eponymous creó un gran impacto cuando fue lanzado en 2010. ¿Cómo te ves en aquel período?</p>
			
			<p id="iw_answer">Estoy realmente sorprendido de que nos las arreglamos para mantener esta situación durante tres años. En realidad queríamos lanzar Infestissumam en 2011, pero no teníamos el tiempo, entonces también tuvimos un cambio de disquera. Pensé que todo el mundo se iba a cansar de nosotros.</p>
			
			<p id="iw_question"> Que es exactamente lo contrario de lo que sucedió …</p>
			
			<p id="iw_answer">Sí, en este momento nos sentimos así, pero no en ese entonces, igual que no sentía confianza de que esto pudiera valer la pena… No seremos novedosos en cinco años, nunca se sabe lo que pasa. Tienes que seguir reinventándote a ti mismo y ser mejor todo el tiempo. Creo que lo que es probable que agregamos en un principio era una buena alternativa a la música contemporánea que está ahí fuera. Incluso si tenemos algún asunto real sobre el que estamos cantando, especialmente en el nuevo disco, hay algún tipo de sustancia “stream”. Ghost se trata escapismo que es contrario a lo que muchas bandas están haciendo que cantan acerca de la vida. “Mis padres están divorciados” o “A la mierda, la vida es una mierda”, todo lo que pasa en todo el escenario actual, donde todo se supone que es tan real y creíble. Lo que estamos tratando de hacer es tan lejano de lo que puede servir como un buen antídoto, aunque no esperamos que nadie se aleje de lo que normalmente es porque les guste la banda. Viene con el paquete: si te gusta una banda en particular, eres llevado a un mundo completo de lo que ellos son. Por lo que representamos alternativa que no exige nada. Usted puede optar por participar si lo desea, mucha gente hace eso, se visten como Papa o se visten como Ghouls, pero no le decimos a nadie que se ajuste a nuestro estilo de vida, porque nadie sabe cuál es nuestro estilo de vida.</p>
			
			<p id="iw_question"> Ghost lanzó una nueva canción en línea titulada ‘Year Zero’ hace algún tiempo. ¿Por qué escogieron esa canción en particular?</p>
			
			<p id="iw_answer">Hay canciones en Infestissumam que pueden ser demasiado similares a algunas de Opus Eponymous en algunos aspectos. Así que queríamos presentar el disco con una canción que sobresalía un poco? Es por eso que elegimos 'Year Zero’, pensamos en hacer un tipo de calentamiento del nuevo álbum con esta canción. 'Year Zero’ es como una aplanadora ahora, se ha convertido en una gran canción masiva, es casi como un ritual que resume gran parte de la competencia de lo que estamos haciendo.</p>
			
			<p id="iw_question"> Y ¿cuál es el asunto de 'I’m A Marionette, una canción grabada originalmente por Abba?</p>
			
			<p id="iw_answer">No creo que hubiera sido muy bueno si hubiéramos grabado una canción Mercyful Fate como cover, habría resultado tan poco interesante, por mucho que a todos nos guste la banda y quisiéramos rendirles un homenaje. No hubiera sido difícil. Necesitábamos encontrar una canción que estuviera a la altura de algún tipo de prebendas y que también fuera cambiante de alguna manera con algunos ángulos que fueran naturales para que fueran tocados por Ghost. El siguiente paso que hemos considerado son las letras, si eran buenos para que Papa las cantara, que es siempre lo más importante. Una versión tiene que funcionar de cierta manera en el tema que estamos tratando de construir. 'I’m A Marionette’ demuestra nuestro punto.</p>
			
			<p id="iw_question"> Usted ha hablado mucho de King Diamond y Mercyful Fate: son todavía muy influyentes en tu ser como artista?</p>
			
			<p id="iw_answer">King Diamond coloreó mucho de mi percepción de lo que un show en vivo debe ser y lo que debe ser la presencia escénica. Es seguro decir que sin él y Mercyful Fate, seríamos exactamente lo mismo, pero sin maquillaje.</p>
			
			Marcus J. West</br></br>
			
			(Fuente: <a href="http://www.ghostcultmag.com/occult-ghosts-and-other-ghouls-an-interview-with-ghost/" target="_blank"> ghostcultmag.com</a>)
		</div>
	</div>
<html>