	<h3 id="titleIntw">Ghost en Sweden Rock Magazine (parte I)</h3></br>
	<p id="iw_question">En las fotos de este artículo los lectores se enfrentarán, en parte, a un Papa Emeritus II en traje de papa, en parte, a un Papa Emeritus II con un vestido de civil en un ambiente familiar que lleva además diferentes pelucas. Eso es, sin duda, confuso para muchos de los lectores. Explique cómo son las cosas.</p>
				
	 <p id="iw_answer">No es más complicado que el hecho de que hay un Gene Simmons que se puede ver en la serie de televisión “Family Jewels” y otro Gene Simmons que se puede ver en el escenario,- dice uno de los Nameless Ghouls guitarristas. Por lo tanto, es la misma persona en las fotos. Uno de ellos es Papa II en una perspectiva oficial, pública y el otro debería ser menos público, pero hay muchas personas que han notado sus “estupideces” y eso es divertido, por supuesto. Es más difícil sobre todo para la gente a la que le cuesta entender las cosas. Eso es lo que hemos descubierto y en realidad es con lo que estamos jugando. Ese es el resultado del experimento.</p>
	
	
	<p id="iw_question">¿Qué experimento?</p>
	
	 <p id="iw_answer">Nuestro experimento de acuerdo al hecho de que nosotros no mostramos demasiado de nosotros mismos. En realidad mostramos mucho más de lo que la gente entiende, dado que es nuestra banda y nuestra música. Pero no ofrecemos las cosas obvias. Anteriormente, eran historias de familia y hoy en día son los miembros de las bandas los que están muy interesados ??en hacer tweets, Instagram y Facebook tanto como sea posible porque no pueden abstenerse de obtener la jodida atención. Eso no quiere decir que no queremos que nuestra banda y lo nuestro se vuelva tan exitoso como sea posible. Pero, por lo menos, no estamos interesados en que se nos distinga a nosotros mismos como individuos. Es interesante lo difícil que puede ser para el público manejar esto. Ahora es sólo Papa II quien también quiere presentarse a sí mismo. Aquí la banda consigue una profundidad, algo en lo que la gente puede interesarse.</p>
	
	<p id="iw_question">Esta ha sido la última aparición del Papa II delante de la cámara antes de que fuera despedido por Ghost y antes de que en el próximo álbum sea reemplazado por Papa III. ¿Cómo tomó Papa II esto?</p>
	
		 <p id="iw_answer">Al igual que la mayoría de la gente es muy difícil para Papa II darse cuenta de sus propios límites y de su propia condición perecedera. Independientemente de lo colorido que quiere ser y de lo mucho que aún trata de ser estrella de rock, sólo será uno, siempre y cuando él esté con nosotros en Ghost. Después puede hacer lo que quiera. Pero en este contexto, su tiempo es limitado, exactamente como fue el tiempo del primer Papa y el tiempo del tercer Papa será. Y del cuarto …</p>
	
	<p id="iw_question">¿Cuáles fueron sus reflexiones sobre el nuevo álbum que se dará a conocer al final del verano o a principios de otoño?</p>
	 <p id="iw_answer">Nuestro concepto es limitado, por lo que siempre se tiene que embellecer el lenguaje. Desde hace un tiempo teníamos ideas acerca de cómo nosotros, a la manera Iron Maiden, podíamos transformar nuestros ingredientes - nuestra mascota, nuestra iglesia en el escenario etcétera - a diferentes épocas y formas de modo que se sintiera interesante. Nunca será King Diamond en realidad ya que no es una narración en ese caso, sino que tratamos de poner al oyente en una perspectiva. El primer álbum Opus Eponymous (2010) se lleva a cabo en el ambiente de una antigua iglesia católica de la vieja escuela. Infestissumam (2013) se lleva a cabo en el tipo barroco de principios del siglo 18, en una iglesia muy en consonancia con el periodo con una decoración de mármol y máscaras venecianas. Con el nuevo entraremos en el futuro, en un período de pre-apocalíptico justo antes se vaya al infierno. A medida que la era digital es tan increíblemente aburrida y poco atractiva, se optó por hacerlo fuera de una visión futura propia de 1920. La urbana gigantesca, con los rascacielos y las máquinas. Un tipo de mundo  de “Metrópoli”.</p>
	 
	<p id="iw_question">Si el concepto ahora es tan estrecho ¿hay algo de lo que se arrepiente y desde el principio habría hecho de otra manera si hubiera tenido la oportunidad?</p>
	
	 <p id="iw_answer">No. En el primer álbum fue sin bastantes matices, porque cuando la música fue escrita no teníamos ninguna idea de que esto se convertiría en algo construido tan públicamente, como en realidad se ha convertido. Ghost era sólo un pensamiento que, alternativamente, se podría hacer. Cuando se concretó como "esto es algo que realmente tiene que desarrollarse”, descubrimos que la expresión muy anal, puberal del primer trabajo era difícil de hacer más de una vez. Sigo pensando que es muy bueno y me encanta este tipo de música y temática. Pero es difícil hacer más de un álbum de esta manera. Tiene un fin. Venom logró hacer tres piezas. Nosotros también tenemos este tipo de canciones en nuestros álbumes dos y tres, pero es difícil de hacer diez canciones en un álbum de esta manera. Tienes que embellecerlo.
	Ya en el segundo disco, y ahora incluso más, no es sólo acerca de la religión. Se trata de personas, acerca de cómo la gente piensa y cómo la gente se siente. Entonces el tema de repente se vuelve mucho más grande. En realidad se puede cantar sobre lo que de alguna manera se relaciona con los sentimientos de los pueblos, el desarrollo o la falta de desarrollo, la lucha o situaciones. Esa es la parte fáctica. Pero siempre hay una trama superficial y una trama subyacente. Esa es la forma en que construimos las letras y el concepto. Entonces esta vaguedad entra y es por eso que es tan difícil mantener una línea intelectual recta en todo el asunto.
	En el primer disco las letras son pura adoración,  tratan de pintar un cuadro del feroz Diablo y el feroz infierno.
	Lo que básicamente hizo que todo el que lea esta revista adore este tipo de cosas. Es Satanás en un trono, calaveras, cruces y serpientes. Eso también es muy acrítico y realmente no crea una perspectiva. Pero tan pronto como se dedique usted mismo más de un cuarto de hora al pensamiento teológico, se da cuenta de que es muy, muy difícil de determinar realmente el bien y el mal. ¿Qué es el mal? Ya en el periódico de hoy se puede ver una cantidad extrema de malas acciones que se están realizando en el nombre de buenas religiones, mientras que ni siquiera puedo pensar más que en tal vez diez obras que se han hecho en el nombre de Satanás.</p>
	
	<p id="iw_question">En la última entrevista para SRM-, en diciembre de 2013, usted era abierto acerca de las palabras, como Satanás en las letras lo cual ha tenido una influencia negativa en Ghost, particularmente en los EE.UU., donde estaciones de radio no quieren tocar las canciones. ¿Eso ha llevado a que la consecuencia sea que Satanás haya desaparecido en el nuevo álbum?</p>
	
	<p id="iw_answer">Tienes que leer las letras a entender, además de las canciones obvias “Majesty” y “Devil Church”. ¿Qué es en realidad más diabólico? ¿Es “Deathspell Omega ”, que no le gusta a más de 500 personas? ¿Es esa la mejor manera para que el Diablo se comunique? Ni puta idea. Slayer, que ha vendido millones de discos, es una mejor manera para que Satanás se comunique, si suponemos que en realidad existe un ser cuyo único propósito es llegar al mayor número de personas posible. Aunque Deathspell Omega tiene algo desde un punto de vista puramente artístico, ellos son teológicamente, y especialmente filosóficamente, unos portavoces mucho más desarrollados. Aquí volvemos parcialmente a lo que hablamos en grandes en términos la última vez: Filosofía y tema versus nuestra voluntad de triunfar. Y ahora Ghost permanece y lanza un gol en el campo que tratamos de tener una idea de lo que parece. Es interesante averiguar si se pueden cambiar sólo pequeños detalles y todavía decir lo mismo, o en realidad empeorar las cosas sin que la gente piense en ello.</br></br>
	Todo nuestro concepto juega con la idea de una religiosidad autoritaria, en donde hay un ser autoritario que define lo que el oyente y el espectador tiene que sentir y pensar. Una cosa que hemos trabajado mucho sobre este tema es arrullar al oyente para que crea que las letras son acerca de algo más de lo que realmente son para evocar la idea de la manipulación. Sin embargo, hay palabras cargadas que nos pueden descalificar de la radio, incluso hay ciertas palabras cargadas que pueden hacer que el oyente crea que hablamos de una cosa, mientras que en realidad se trata de algo completamente diferente.</p>
	
	<p id="iw_question">
	¿Puede dar un ejemplo?</p>
	
	<p id="iw_answer">
	Una de las nuevas canciones se llama “Cirice”. Si se pronuncia de esta manera, suena como un nombre, como Clarice. Papa III le habla al oyente y canta sobre una amenaza exterior y la ansiedad que comparte con el oyente. Y más tarde, en un momento determinado en el coro, hay una vinculación. “I feel how you feel. You and I, we cohere.”  De alguna manera, automáticamente se vuelve íntimo, casi como un apego romántico. El punto es que “Cirice” en realidad tiene su origen en el término “cirice” del inglés antiguo y ahí es donde las palabras “church” y “kyrka” tienen su origen. Eso es exactamente como siempre lo hacía la iglesia. Ellos implementaban una amenaza global y una solución para ella. Un concepto de totalidad que mantiene a los subyugados en un arreglo, plano y simple. Este es un ejemplo de cómo una canción en realidad se disfraza en una forma, ya que debe ser interpretado por el oyente en cierta manera, pero en realidad significa algo diferente.</p>
	
	<p id="iw_question">¿Hay mensajes al revés en alguna canción de Ghost?  ¿Han ocultado algo que nadie ha descubierto?</p>
	
	<p id="iw_answer"> En una de las nuevas canciones,  "From The Pinnacle To The Pit",  tenemos un solo que es backwards que compuse hacia atrás y fue grabado al revés.</p>
	
	<p id="iw_question">¿Cómo sucedió eso?</p>
	
	<p id="iw_answer"> En el pasado las bandas se sentaban en estudios demasiado costosos con demasiado tiempo.</br></br>

	El proceso se ha vuelto similar hoy en día, cuando te sientas más en un estudio y haces música y  ensayas menos. Entonces, fácilmente pasa que te tropiezas con las ideas ya que gran parte pasa durante el proceso del demo. Una de las canciones tenía un solo que se sentía muy concienzudo y sombrío. Así que tomamos una parte de una sección anterior de la canción, la hicimos hacia atrás y la pusimos ahí para ilustrar un solo. Sólo porque durante la fase de demo debíamos ser capaces     de escuchar “Ajá, aquí debe haber un solo de guitarra”. De otra manera sólo habría un respaldo vacío y el oído podría engañarse y pensar que nada sucede allí. Eso se convirtió en algo que sobrevivió a la fase de la idea: “Aquí tiene que haber un solo hacia atrás.” Para nosotros se vuelve extra desordenado, ya que básicamente salpicamos todo para alcanzar la “pura imposibilidad”.</p>
	
	(Fuente: <a href="http://www.zebu.co.nf/" target="_blank">zebu.co.nf</a>)
				