<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
	<head>
		<link rel="stylesheet" href="../css/style.css" />
		<link rel="stylesheet" href="../css/bootstrap.css" />
		<link rel="stylesheet" type="text/css" href="../js/zoombox/zoombox.css" /><link rel="stylesheet" type="text/css" href="http://grafikart.fr/css/zoombox.css" /> 
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
		<link rel="stylesheet" href="../css/stylesheet.css" type="text/css" charset="utf-8" />
	</head>

	<div class="interview" >
		<div id="scriptum-text">
			<h3 id="titleIntw">GHOST JAGERMEISTER MUSIC TOUR 2013 (Entrevista - Traducción)</h3></br>
			<img src="../img/scriptum/ghost_jagermeister.jpg"/></br></br>
			
			<p id="iw_answer">Hola hijos de Bournemouth, soy un Ghoul sin nombre de Ghost. Estamos aquí esta noche rockeando en el Tour Jägermeister.</p>
			
			<p id="iw_answer"> Literalmente, somos una banda de rock, pero para entender completamente el aspecto conceptual creo que tenemos que ser considerados como algo que está en la zona del sonido crepuscular entre el teatro y el rock, más como una película tal vez, suena muy pretencioso, pero eso es básicamente lo que hacemos.</p>
	
			<p id="iw_answer">Obviamente que está el asunto de que hay gente que de alguna manera no  entiende el concepto de la banda porque sus personajes son, abiertamente,  una secta satánica. Ese es el show. Hay una idea falsa en general que sólo porque se está una banda de rock lo que se dice en los confines del espectáculo es algo que se vive y se respira, y se necesita y se sueña … Obviamente, todo lo que estamos diciendo, lo que estamos cantando viene de alguna parte y sólo porque estamos diciendo que lo que estamos haciendo es un espectáculo no quiere decir que todo lo que estamos diciendo es algo falso, pero indudablemente, permanecer en el interior de la caja ortodoxa satánica, como lo implica nuestro show, deja muy poco espacio intelectual y nosotros, como individuos y allí de donde todo viene en lo que respecta a Ghost, es, obviamente, de un significado más profundo entonces hemos elegido … esteroides y lo hemos llamado Ghost. Pero usted puede elegir como parte aceptante, al ser un miembro de la multitud, puede elegir si quiere tomarlo literalmente o si quiere ir poco profundo y hay un poco de todo, siempre hay dos lados en cada letra de las canciones, en el concepto mismo (de Ghost).</p>
			
			<p id="iw_answer">Hemos dicho desde el primer día que queríamos hacer una banda grande, así que si alguien que no leyó esa parte no podemos tenerle lástima. Venimos de movimientos underground, por lo mismo, entendemos completamente lo que están diciendo, entendemos completamente cómo es ser un fan de una banda que vende o que siente cómo han traicionado su esencia, pero creo que en nuestro caso,  se tiene que prestar atención a lo que hemos estado diciendo todo el tiempo. Sólo pasa que nosotros comenzamos  en un lugar en el que conseguimos algunos fans, del tipo de fans que nos gustaban, luego, algunos de ellos podrían ser muy celosos de lo que les gusta y puede que les resulte incómodo cuando alguien  más le toma gusto a lo que ellos atesoran. Pero creo que usted, básicamente, los traiciona cuando vende más de 500 discos, eso es viejo  y yo conozco a varias personas que son típicos porteros en términos del tipo de pensamiento anal del interior de la caja pero que aun así todavía les gustamos y entienden que estamos haciendo exactamente lo que nos propusimos desde el principio: queremos ser una gran banda de rock teatral. Si quieres ser una banda de rock teatral necesitas tener un grupo determinado con el fin de sacar un show y no estamos aquí para ir hacia atrás, para hablar hacia atrás (al revés) tal vez, pero no para caminar hacia atrás.</p>
			
			<p id="iw_answer">El título del álbum, <b>Infestissumam</b>, significa la mayor amenaza y en todo el álbum, de una forma u otra forma todas las letras tratan de cómo la humanidad se relaciona con la presencia del demonio y del Anticristo y sí, básicamente, la contaminación de una presencia diabólica y que históricamente ha adoptado diversas formas que han sido, obviamente, una cabra, las brujas y todo eso, pero en general es realmente acerca de la forma femenina y el sexo que es por lo general lo que es más probable que se considere como algo satánico y que tiene un efecto diabólico en los machos predominantemente. Así que, básicamente, es un disco lleno de obscenidades pared a pared .</p>
			
			<p id="iw_answer">La gira de Jaeger ha sido muy exitosa para nosotros hasta ahora porque, de nuevo volviendo a lo que dije antes, nuestra intención de crear un espectáculo un poco más grande, esto es una gran manera para que flexionemos nuestros músculos en recintos más grandes para mucha gente y este es un tour pre-álbum, en torno a que viene después, así que obviamente es algo extraño comenzar un final con canciones que nunca nadie ha escuchado, pero ese es un riesgo que estábamos dispuestos a tomar porque creemos que con nuestro último álbum disponible únicamente, hemos pasado casi dos años en gira tocando las mismos nueve canciones en el mismo maldito orden, entonces quieres sonar algo emocionante y estábamos alegres de poder hacer más y ser capaces de quitar algunas cartas que podrían no esperarse y en cuanto a tocar con bandas que no suenan como nosotros también, estamos totalmente bien. Creemos que lo que estamos haciendo es diferente, no es ni mejor ni peor que los demás, pero nosotros preferimos permanecer diferentes de todo lo demás. Y si tuviéramos que vivir conforme a la regla de que sólo vamos a tocar con bandas que se nos parecen en algo, que deban  tener cosas en común con nosotros sea lo que sea,  semejanza de  imagen,  o el rock lo oculto o lo que sea, consideramos que eso no es bueno para nadie, me refiero a que , hay un montón de scenesters que creen que ver 15 bandas que suenan igual en un espectáculo es una buena cosa; creo que disminuye totalmente a todas estas 15 bandas y si fuéramos a brillar lejos de tocar con … yo no sé, bandas deathcore, no seríamos capaces de tocar en ningún festival. Eso es lo contemporáneo, deathcore, screamo todas esas cosas, no  los escuchamos, pero nos invitan a tocar a estos festivales así que por qué no, además parece que va bien así, somos el dolor en el pulgar.</p>
			
			(Fuente: <a href="http://www.youtube.com/watch?v=d2v1TEFZChY" target="_blank">youtube.com</a>)
		</div>
	</div>
<html>