<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
	<head>
		<link rel="stylesheet" href="../css/style.css" />
		<link rel="stylesheet" href="../css/bootstrap.css" />
		<link rel="stylesheet" type="text/css" href="../js/zoombox/zoombox.css" /><link rel="stylesheet" type="text/css" href="http://grafikart.fr/css/zoombox.css" /> 
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
		<link rel="stylesheet" href="../css/stylesheet.css" type="text/css" charset="utf-8" />
	</head>

	<div class="interview" >
		<div id="scriptum-text">
			<h3 id="titleIntw">Noize: Ghost - Entrevista</h3></br>
			<img style="margin-left:30px" src="../img/scriptum/juin_noize_ghost.jpg"/></br></br>
			
			<p id="iw_question"> Una entrevista en vivo con <b>Ghost</b> es sin duda una oportunidad para ver de primera mano el grado en que la banda sueca juega con su propia imagen y cuánto se basa en la ficción de personajes catapultados en un par de años desde el anonimato “para forzar” al anonimato “por elección “. ) A continuación, nos encontramos con el guitarrista principal de la banda en el backstage de la Zona Roveri inmediatamente después de la prueba de sonido: las primeras respuestas a las preguntas de la apertura llegan sin siquiera comenzar la entrevista, ya que el "demonio”, conocido como &Delta; (delta, símbolo alquímico-delta- de fuego o lo que quieras) se ve exactamente como en el escenario, con velo y una máscara de plástico que funcionan como una doble cobertura de sus rasgos, con el colgante del crucifijo invertido que es el logotipo de la banda y un apretón de manos simple y el impersonal “encantado de conocerte "como bienvenida. La única concesión a la calurosa tarde de Bolonia es el hábito en versión "verano”, a diferencia de los pesados ropajes monacales de la sesión fotográfica, que aún deja descubierto sólo las del manos interlocutor - el cuál resultará un personaje decididamente gentil, locuaz y con sentido del humor -.</br></br>La primera pregunta se refiere al aspecto creativo de su música, ¿cuánto tiempo suele dedicar a escribir la música y las letras, y cuánto a la preparación de lo visual y el teatro en sí?</p>
			
			<p id="iw_answer"> No hay una fórmula exacta, algunas canciones salen después de un largo razonamiento otras muy rápidamente. Yo diría que las letras suelen venir al final, antes de encontrar el trabajamos primero encontrando las melodías vocales. Por lo general, yo diría que la mayoría de las canciones empiezan con una idea de la melodía vocal y algunos acordes, una melodía de la canción, pero digamos que todo está muy orientado a la idea original de la melodía vocal con la tesis de riffs para enfatizar la propia melodía.</br></br>Obviamente, hay excepciones a la regla, algunas piezas como Ritual partieron de los riffs de guitarra.</br></br>En cuanto a la estética, si el primer disco se ha grabado con la idea de teatralidad, ahora con el segundo disco que tenemos más experiencia, hemos aprendido de la última gira de alguna manera de predecir cuáles serán las canciones que formarán parte de nuestra alineación. Ahora podemos pensar “ok, esto es adecuado para la apertura, este otro para el cierre de la serie …”, por ejemplo “Monstrance Clock” ya estaba pensada como la canción de cierre del disco y del set desde el primer demo, ya que tiene una sensación de “plenitud”, así como “Per Aspera ..” al comienzo de la serie. Obviamente también hay canciones que por la misma razón no son adecuadas para ser tocadas en directo.</p>
			<img src="../img/scriptum/juin_noize_tumblr_inline_moojo98FIY1qz4rgp.jpg"/>
			</br></br>
			<p id="iw_question"> ¿Cómo contactaron al compositor David Campbell para el tratamiento de los arreglos de las canciones de su último disco? ¿De qué manera lo influyó?</p>
			
			<p id="iw_answer">En realidad no ha hecho los arreglos, los coros ya habían sido arreglados por nosotros, si escuchas el demo te darías cuenta de que son exactamente lo mismo. El único problema es que cuando teníamos que grabarlos, no encontramos ningún coro que quisiera cantar  lo que queríamos  que queríamos que se cantara, así que debido a problemas de tiempo tuvimos que transferir esta parte de la obra en Los Angeles. No podríamos estar presente en persona, así que tuvimos que encontrar una persona que guiara el trabajo, esta persona fue David Campbell. Básicamente, él escuchó lo que el coro cantó en el demo y lo transcribió para que un coro de cuarenta personas pudiera cantarlo, pero no añadió nada,  todo es harina de nuestro saco.</p>
			
			<p id="iw_question"> Cuando los vi en el escenario por primera vez, era 2011 y estaban en el Festival Roadburn en los Países Bajos, después de dos años, todo parece haber cambiado: ha pasado de ser “la banda de la semana” seleccionados por Fenriz a titulares de giras europeas … “¿qué  ha cambiado más para usted? ¿qué cosa se ha mantenido exactamente igual?</p>
			
			<p id="iw_answer">Me gustaría decir que hoy en día somos una mejor banda, pero yo no creo que sea del todo cierto (risas). Obviamente, dos años en el camino nos convierten en un grupo más profesional, mejoramos desde muchos puntos de vista, se tiende a hacer lo que hace de una forma más precisa.</br></br>La mayor diferencia que creo es que ahora tenemos un segundo disco, por lo que incluso el set en vivo es cada vez menos evidente ya que no estamos obligados a tocar el 100% de piezas del primer disco, sin embargo, me gustaría decir que todo el proceso pasado, presente y futuro, incluso si habláramos de un tercer disco, será la continuación de la idea que teníamos en el año 2009 cuando empezamos la banda.</br></br>La idea original detrás de Ghost es bastante compleja, por lo que tardaremos 4 o 5 años en terminarla, sin duda cambiaremos a lo largo del camino, pero la mayoría de los aspectos siguen y cuanto más avanzamos más nos acercamos a la realización del proyecto inicial.</p>
			
			<p id="iw_question">Así que diría que antes de verlos en su forma completa, ¿qué refleja plenamente lo que tenía en mente, serían necesarios cuatro o cinco años?</p>
			
			<p id="iw_answer">Bueno, espero que no (risas). Tal vez más tarde … Lo pondré de esta manera, ahora somos cabeza de cartel en los festivales, como el Sonisphere en Milán, pero las personas que vendrán a ver las localidades más pequeñas no asistirán al mismo show  en el que tenemos toda la producción necesaria para nuestro espectáculo, por lo que aún hoy en día en realidad no es nuestro espectáculo "A”, sino el “C” sobre la hipotética escala de la producción en cuestión.</br></br>También tocar en frente de de tanto público como en el Sonisphere, por ejemplo, pero en plena tarde, yo diría que es el “mal menor” para poder volver en el futuro a esos lugares y montar un espectáculo en nuestro mejor momento. </p>
			
			<p id="iw_question"> Pero ¿hoy prefieren lugares más pequeños o es importante tocar en frente de miles de personas?</p>
			
			<p id="iw_answer">Yo diría que un término medio entre los dos, obviamente, depende de lo que entiendas por “grande”, es el lugar ideal para mí, yo diría que con cerca de dos mil espectadores, de modo que se pueda “sentir” el público, un escenario lo suficientemente grande para dar cabida a nuestra producción pero que deje la posibilidad de ver a la gente de las primeras filas. El tamaño que prefiero es el de los teatros, ya que tanto nosotros como el público son capaces de ver a la perfección y sin que las distancias anulen la una o la otra parte. </br></br>Como Rammstein centra su atención en su cantante Till y lleva al extremo su figura de super macho, super viril, nosotros tenemos un Papa que es un líder  similar pero diametralmente opuesto, más andrógino y más del “tipo mafia”, ladra mucho, pero nunca dará la impresión de querer morder (risas).</p>
			
			<p id="iw_question"> ¿Cuáles son las bandas que más te han inspirado? Lo que amabas, lo que te gusta hasta hoy y cuáles encuentras que están más “dentro” de tu música?</p>
			
			<p id="iw_answer">Estamos muy influenciados por todas las bandas que han hecho “shock rock” en el pasado como Kiss, Alice Cooper, David Bowie, así como los Rolling Stones, que a pesar de que nunca se disfrazaron a finales de los años 60 tenían una manera única de presentarse en escena, fueron innovadores en la creación de un imaginario que circundara a la banda.</br></br>Hoy en día quizás la banda de la que más nos inspiramos es Rammstein, que son una especie de versión desplazada diez años en el futuro de aquello que queremos hacer como banda. Creo que todo el mundo subterráneo de las banda screamo que basan todo en el hecho de ser uno con el público, ya sabes, “Hey, yo el artista y tu el fan, somos lo mismo” no nos pertenece a todos, nosotros no queremos ser que Ghost sea como su público, queremos que Ghost sea … boom! (Risas) pomposo y memorable.</p>
			
			<p id="iw_question"> ¿Son una banda que compone durante las giras o salen para para concentrarse en las presentaciones en vivo?</p>
			
			<p id="iw_answer">De hecho, no hemos tenido un verdadero periodo dedicado al demo para el tercer álbum, pero estamos definitivamente abordando este asunto así que creo que ya este verano comenzaremos a dedicarle seriamente el tiempo y grabar el primer demo.</br></br>Tenemos una idea clara del tercer disco, cómo deberá sonar el nombre… ya sabemos la temática que el disco tendrá entonces es mejor empezar ahora, cuando toda la atención está puesta en el disco actual … para responder a tu pregunta, sí, somos una banda que compone incluso durante la gira.</p>
			
			<p id="iw_question"> Hablando de Rammstein, llegué a ver la edición especial de su disco junto con un consolador … que también han tomado esta idea de ellos? Lo han probado personalmente?</p>
			
			<p id="iw_answer">Sí, habíamos visto sus envases con un consolador pero personalmente nunca lo he probado, he visto nuestro consolador y lo he tenido en la mano como lo hice con sus consoladores … “es impresionante” (risas) …</p>
			
			<p id="iw_question"> Esto para hablar en general acerca de sus problemas con la censura …</p>
			
			<p id="iw_answer">Obviamente hemos tenido varios. Personalmente veo la censura realmente como un estado soberano propio, deben someterse a las normas si quieren vender su material.</br></br>Por ejemplo, con respecto al concepto gráfico al interior … no sé cuántas bandas de Universal han chocado con impresoras que se niegan a imprimir el disco … tienen una política muy estricta, ya sabes, América es América y usted puede demandar a cualquiera por cualquier cosa. Más específicamente, aunque la sociedad matriz no tenía ningún problema dando su aprobación, tuvo que renunciar por temor a que sus empleados pusieran una demanda de acoso sexual. Entiendo que puede parecer ridículo, pero en los EE.UU. si usted piensa que su jefe lo obliga a imprimir pornografía se le puede demandar.</br></br>Luego recibimos entonces el “no” de cuatro impresoras, antes de encontrar la quinta que no tuvo ningún problema en aceptar el trabajo.</br></br>En cuanto a el consolador, queríamos que fuera una verdadera edición especial y que cada disco viniera con la “caja consolador”, porque el disco en sí tiene un subtexto preciso con respecto a la libertad sexual, especialmente la femenina, incluso fuera del matrimonio, así que queríamos un consolador junto conel  cd “para liberarse" y además un estimulador anal para … bueno … (todos los presentes se ríen).</br></br>Obviamente estábamos bromeando y queríamos jugar irónicamente con los temas del disco, pero fue seriamente la forma en que habíamos planeado presentar el disco … obviamente, cuando la compañía discográfica vio nuestro proyecto reaccionó como “Oh, un consolador?” E inmediatamente después … (hace el mimo de los pulgares hacia abajo y el sonido de las respuestas incorrectas de los programas de concurso), así que tuvimos que recurrir a la venta de las dos ediciones separadas, que sigue siendo divertido, pero le quita el sentido de singularidad a la idea que hemos querido dar.</br></br>En este caso, en lugar de hablar de la censura se habla de de las políticas corporativas, para el sello se puede hacer lo que quieras mientras eso no los afecte… lo mismo para el nombre de la banda, nos llamamos Ghost  y no Ghost B.C. pero el sello debe, sin embargo, publicar el disco en Estados Unidos y esta es la única manera de no violar ningún derecho de autor …</p>
			
			<p id="iw_question"> ¿Ya tienen planes para la futura publicación de un álbum en vivo o un DVD, tal vez?</p>
			
			<p id="iw_answer">De hecho, tenemos la intención, de aquí al verano que vienr, de grabar nuestro show, pero hay varias cosas que todavía tenemos que mejorar, por ejemplo, tenemos que encontrar un lugar para hospedarnos allí durante dos noches seguidas y poder establecer nuestro espectáculo esencialmente completo… sí, definitivamente vamos a grabar material para un DVD porque queremos dejar un rastro de lo que estamos haciendo ahora, ya que en la óptica del tercer disco a futuro todo será muy diferente.</p>
			
			<p id="iw_question">Volviendo a los Estados Unidos, ustedes grabaron el disco allí así que tengo curiosidad por saber cómo se relacionaron con una realidad musical tan diferente y con un enfoque tan lejano al de una banda del norte de Europa</p>
			
			<p id="iw_answer">Por un lado grabamos en Nashville y cabe señalar que Nashville es una cosa y el resto de los Estados Unidos es algo completamente diferente … Creo que es la ciudad más liberal en el Medio Oeste, pero todavía es una ciudad “super vaquera.” Yo no quiero entrar en un discurso político pero mientras Nashville es quizás la única ciudad amable que nos encontramos, sólo hay que salir durante veinte minutos en la carretera y te encuentras en medio del Ku Klux Klan, es horrible …</br></br>Para nosotros siempre es emocionante encontrar en las ciudades que tienen un alto número de personas que trabajan en el campo de la música por ejemplo, Nashville es increíble, incluso tiene toda una calle en la que todos los grandes Major tienen su sede, Universal, Warner, BMG … están todas , pero se ocupan principalmente en el país. Así que para nosotros sigue siendo una experiencia muy interesante, a pesar de que escuchamos la misma música no somos grandes fans del country, nos sentimos como si hubiéramos llegado a una convención de Star Trek a pesar de ser fans de Star Wars (risas), están las naves y resto no es nuestro campo de juego.</br></br>Fue una gran experiencia, tienen un montón de grandes estudios y todo es muy, muy profesional … pero definitivamente vamos a elegir otro lugar la próxima vez (risas).</p>
			
			Entrevista hecha por <i>Daniele Gatti</i></br></br>Traducida al español por Anabell Lamp</br></br>
			
			(Fuente: <a href="http://www.noizeitalia.com/ghost-intervista/" target="_blank">noizeitalia.com</a>)
		</div>
	</div>
<html>