<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
	<head>
		<link rel="stylesheet" href="../css/style.css" />
		<link rel="stylesheet" href="../css/bootstrap.css" />
		<link rel="stylesheet" type="text/css" href="../js/zoombox/zoombox.css" /><link rel="stylesheet" type="text/css" href="http://grafikart.fr/css/zoombox.css" /> 
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
		<link rel="stylesheet" href="../css/stylesheet.css" type="text/css" charset="utf-8" />
	</head>

	<div class="interview" >
		<div id="scriptum-text">
			<h3 id="titleIntw">Papa Don’t Preach (entrevista)</h3></br>
			<img style="margin-left:130px" src="../img/scriptum/papadontpreach.jpg"/></br></br>
			
			Metal Hammer, mayo de 2013.
			</br>
			Por Ben Myers</br></br>
			<p id="iw_question"> El sol está saliendo en Melbourne, Australia. La luz brilla a través de un espacio entre las cortinas de una anónima habitación de un hotel.</p>
			<p id="iw_answer">“El sol está saliendo, infortunadamente”, dice uno de los cinco Nameless Ghouls, quien o se ha acabado de despertar o no ha ido a la cama todavía. Es difícil de decir. “Pero se pondrá de nuevo, eventualmente. En celebración de la renuncia del líder de la Iglesia Católica, necesito poner un poco más de leche en mi café. Me excusa?”</p>
			<p id="iw_question"> Entre el tiempo en que [Metal] Hammer concertó esta entrevista con Ghost en Suecia y los localizó ocho días y más o menos 10.000 millas luego, la iglesia católica ha sido sacudida por más acusaciones de comportamiento inapropiado de uno de sus eminentes cardenales y su líder –el Papa mismo- se ha convertido en el primero en renunciar en 600 años. Mañana abandonará el Vaticano y adoptará el nuevo título de “Papa Emérito”. Mientras el Ghoul prepara su café la idea nos llega a la mente: conocemos el remplazo papal perfecto. Se llama Papa Emeritus II. Es el “nuevo” cantante de Ghost y aunque tiene una filosofía diferente ya tiene la corona.</p>
			<p id="iw_answer"> “Bueno, yo no estaría interesado”, dice el Nameless Ghoul. “Pero Papa II puede estarlo. Estas últimas semanas han sido un poco confusas para él. La idea puede haber cruzado por su mente pero él ya tiene un nuevo trabajo con nosotros ahora. Como la iglesia, nosotros estamos entrando en una nueva era con un nuevo Papa”.</p>
			<p id="iw_question"> Una rápida recapitulación antes de que las cosas se vuelvan confusas. Como ya sabrán, <b>Ghost</b> llegó de la nada, su concepto se alcanzó completamente con su debut Opus Eponymous con el sello Rise Above en 2010.</br></br>Pero para el lanzamiento del nuevo álbum, Infestissumam, los Nameless Ghouls remplazaron al líder Papa Emeritus por el nuevo cantante Papa Emeritus II durante una presentación en diciembre de 2012. Sólo que es el mismo hombre. Quizás. Y es la persona que nos habla ahora- pero, en definitiva, se supone que nosotros no sabemos que es él. Aunque la casa disquera no nos dirá con quién estamos hablando. Pero lo sabemos. Sabemos que es él. Papa Emeritus I y II. ¿Confuso? No lo es. Cuando todo está dicho y hecho, es sólo rock’n roll.</p>
			<p id="iw_answer"> “Nunca se vio el ritual atrás del escenario en donde, al sonido de Tu eres la Voz, Papa II fue ungido de lo que nosotros llamamos “la nueva voz”” masculla Papa I/Papa II/ Nameless Ghoul.</p>
			<p id="iw_question"> Un momento. Quiere decir You’re The Voice ¿la poderosa balada de los 80 de John Farnham? “Eso es exactamente lo que quiero decir. Tienes que entender que ellos son dos muy diferentes personas, pero la voz y el patrón de movimiento de Papa I fueron básicamente transferidos a Papa II. Es casi como aquella antigua costumbre de kung fu de enseñar la antigua cultura religiosa, con el mono y el tigre ¿entiendes lo que quiero decir?”</p>
			<p id="iw_answer">“Hay una ligera diferencia de edad. El viejo Papa estaba por los 80, mientras que Papa II está por los 50, quizá los 55. Así que Papa II es un poco más…vívido”. ¿Habrá un momento en el que Papa II le pase su espíritu a Papa III y luego al IV y V? Ustedes podrán ser la banda que nunca muere. “Posiblemente. Pero sabes, nos sorprendimos tanto de que nadie viera este cambio venir. De verdad. Realmente pensamos que era tan obvio que esto pasaría”. Bueno, sí parece obvio ahora que nos lo ha explicado. ¿De pronto la gente no les estaba prestando suficiente atención a ustedes y a la banda? “Creo que el mundo entero no gira alrededor de nosotros”. Quizás algún día lo hará.</p>
			<p id="iw_question"> <b>Ghost</b> es una banda que está en la cúspide. Mientras permanezcan tienen el potencial para ser la primera banda en hacer que un género marginal –doom- llegue al mainstream. Ellos podrían, posiblemente, ser (susúrrenlo) la primera banda doom-pop. El debut con una firma grande, Infestissumam, es un álbum para aquellos que han estado esperando baladas en piano acerca de la putrefacción, o que deseaban que Ville Valo cantara canciones de amor acerca de cadáveres. Es una colección para aquellos que sueñan con montar La Profecía: El Musical, protagonizado por King Diamond y Michael Ball, o aquellos que se preguntaban cómo podrían haber sonado The Doors si hubieran festejado sobre huesos de chivo en una sepultura escandinava en vez de haberlo hecho sobre naranjas en el sol californiano. Ghost es una banda para gente a la que le gusta ABBA y Cathedral, o que vería el Factor X si permitiera versiones de Bewitched de Candlemass y fuera presentado por un “Simon Cowl”.
			</br></br>
			Pero ellos también son interesantes porque son una banda que honra una infalible devoción a Satanás, y todavía tiene un ojo en las ventas de discos y en los escenarios que esperan ser llenados.  La adoración al Demonio es un aspecto intrínseco de Ghost, pero de esa manera, usted sospecha, es una evidente ambición de volverse tan grande como Manson o Slipknot –dos similarmente grandiosos artistas a quienes ellos se parecen retóricamente, si no musicalmente.</p>
			<p id="iw_answer"> “Es interesante que mencione La Profecía porque es un retrato realista y fascinante de la llegada del Anticristo a la Tierra”, dice Papa II. “Es sobre el ascenso de un hombre al poder. Pero hacia la escena final de la trilogía el escritor, de repente, tiene la mano de Dios que desciende y pone fin a todo. Es completamente estúpido. Y eso resume un montón de asuntos, para mí, acerca de las opiniones de la gente sobre el satanismo y la adoración al demonio. Nuestro primer álbum tiene una gran cantidad de matices. Opus Eponymous tenía un significado literal: era acerca de la ultra ortodoxa adoración al demonio que estimuló nuestro apetito por el horror, el rock viejo y el metal underground, que podía existir sin pensamiento intelectual. Pero también exploramos las ideas filosóficas subliminales y teológicas. Por ejemplo, en un mundo de cabezas huecas, todo lo bueno es visto como algo Divino y de todo lo malo se culpa al Demonio. Sin embargo, es la Iglesia la que promueve un montón de cosas que son genuinamente malas para la humanidad. Y eso es básicamente lo que es Ghost. Nunca una institución ha puesto a sus seguidores en semejante confusión. Irónicamente, no estamos invirtiendo lo que hace la iglesia –básicamente estamos haciendo lo mismo. Sólo hemos puesto un pequeño bigote sobre ella para llamar la atención.”</p>
			<p id="iw_question">Con el primer álbum ustedes estaban “creando la banda sonora para el fin de la humanidad”. ¿Estas ideas se mantendrán en Infestissumam? “El nuevo álbum es ante todo acerca de la presencia del demonio”, dice Papa II, calentando el tema. “Tiene que ver con la relación que el individuo tiene con la presencia de la oscuridad, y lo que identificamos como el mal. Tiene que ver con asuntos reales. Cada una de nuestras canciones apunta hacia el fin del mundo. Porque todos están corriendo alrededor como idiotas tratando de encontrar su propio camino cuando realmente todos saben que para sobrevivir a una crisis económica o a una catástrofe natural tienen que empujar juntos. Todos saben eso, pero en cambio escogen hacer su propia cosa”. ¿Pero no es eso lo que hace a los humanos, humanos – el libre albedrío? “Exacto. Y eso es el demonio. Ese es el Anticristo”.
			</br></br>
			Un hombre articulado y reflexivo, Papa Emeritus es mucho menos seco de lo que aparece en impreso. Durante la entrevista hay risas y divagaciones dentro de aspectos más mundanos de lo que es ser una banda. Como lo absurdo que es para una banda de doom usar mantos en el sol de mediodía. Pero por el momento, sudar bajo el sol es un pequeño precio que hay que pagar para alimentar la mitología de la banda y construir una base de seguidores.</p>
			<p id="iw_answer"> “Para instalarse en los corazones de los seguidores, el misterio es importante”, explica. “La relación fan/banda es basada en el amor platónico. Tiene que ver con el deseo sexual, pero se mantiene sin consumar. En el rock, un hombre heterosexual casi puede experimentar el enamorarse de otro hombre porque puede encontrarlo muy persuasivo o interesante. El misterio contribuye en eso. Nuestra anonimidad nunca fue un movimiento comercial – fue una elección estética – pero viendo lo que ha resultado quizás nos distingue. Nosotros no mostramos una desesperada necesidad de aceptación como ocurre a otras bandas”.</p>
			<p id="iw_question"> ¿Piensa que más bandas se beneficiarían de un aire de misterio? “Hay un montón de bandas que son sólo tipos con tatuajes cantando (adoptando un sarcástico acento norteamericano), “¿Por qué hombre? Mi padre hizo esto. Él no hizo aquello…jódete!” Eso no es muy brillante. Creo que somos multifacéticos y tener buen sentido del humor es muy importante. Nos vemos a nosotros mismos no solamente como un acto de rock’n roll, sino también desde una posición cinemática y de autor. Sobre el escenario somos una entidad diferente a lo que somos en nuestras vidas privadas. Piensa en las películas: a menudo en las de horror, suspenso o dramas, un simple chiste libera. El humor es importante para sofocar la tensión perturbadora. Muchas bandas se toman a sí mismas muy seriamente”.
			</br></br>
			Como lo hacen, ocasionalmente, los seguidores. Un ascenso tan rápido –Ghost tocaron para alrededor de 1000 personas en su primera presentación- inevitablemente suscita críticas desde esquinas fundamentalistas de la hermandad metalera. ¿Están tranquilos con la transición de Rise Above a Universal?</p>
			<p id="iw_answer"> “Estamos conscientes de que hay una expectativa en ventas ahora”, dice Papa II. “Estábamos en una disquera ecléctica, pero nos hemos convertido en una banda que necesita “romper”. Nuestra idea siempre ha sido ir hacia producciones más grandes. Más público. Todo más”.</p>
			<p id="iw_question"> El viejo Papa II ciertamente tiene buena conversación y si el nuevo sencillo, Secular Haze, es algo para entretenernos mientras tanto, Ghost están solamente preparándose. El único inconveniente de las subidas rápidas son las caídas rápidas. Esto nos deja una pregunta: ¿en dónde se ven en 10 años?</p>
			<p id="iw_answer"> “Por la naturaleza de esta banda, no está garantizado que seamos interesantes por largo tiempo”, dice. “Tenemos planeados dos álbumes más y aspiramos a tocar en grandes escenarios. La parte más dura es saber cuándo parar. No queremos aburrirnos ni a nuestros seguidores. No seremos una máquina de correr y entendemos perfectamente que Ghost no estará ahí para siempre”</p>
			</br></br>
			Traducido por Anabell Lamp
		</div>
	</div>
<html>