<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
	<head>
		<link rel="stylesheet" href="../css/style.css" />
		<link rel="stylesheet" href="../css/bootstrap.css" />
		<link rel="stylesheet" type="text/css" href="../js/zoombox/zoombox.css" /><link rel="stylesheet" type="text/css" href="http://grafikart.fr/css/zoombox.css" /> 
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
		<link rel="stylesheet" href="../css/stylesheet.css" type="text/css" charset="utf-8" />
	</head>

	<div class="interview" >
		<div id="scriptum-text">
			<h3 id="titleIntw">Under The Gun: Ghost - Entrevista con un Nameless Ghoul</h3></br>
			<img style="margin-left:100px" src="../img/scriptum/underthegun.jpg"/></br></br>
			
			Por Brenton Harris</br></br>
			<p id="iw_question">Sin lugar a dudas, <b>Ghost</b> es una de las bandas más interesantes de la música moderna. Una banda anónima que opera dentro de una cultura obsesionada con la celebridad, el quinteto sueco ha logrado obtener un nivel de éxito híbrido que la mayoría de las bandas en su género sólo podían soñar y todo esto sin dejar de estar firmemente envuelta en el misterio. Ellos son más un experimento artístico inmersivo que  una simple banda de metal. Ghost es un espectáculo que resulta, a la vista, totalmente convincente en un entorno real, con el vestuario, la iluminación y el irónico escenario,  se unen todos en una cuidadosa coreografía aunque completamente caótica para ofrecer una experiencia verdaderamente memorable.</p>

			<p id="iw_answer">Nada de esto iba a funcionar, por supuesto, sin la música, que es en sí misma una de las más logradas del metal, técnicamente competente y francamente inquietante de todas la producidas en los últimos tiempos. La combinación de todos estos elementos ha permitido que Papa Emeritus II y su banda de Nameless Ghouls haya alcanzado un lugar único en el ámbito de la música pesada, en la que son anunciados por otros músicos (entre ellos Phil Anselmo y Dave Grohl) , amados por la crítica y adorados por una legión de dedicados fans quienes, a la vez, mantienen su identidad en un secreto profundamente protegido.
			</br></br>
			Actualmente, de gira por Australia en apoyo de su excelente segundo álbum, Infestissumam, y su EP de versiones producido por Dave Grohl, If You Have Ghost, nos sentamos con uno de los improbablemente corteses y totalmente disfrazados Nameless Ghouls en el backstage del festival Big Day Out en Sydney para discutir todo sobre Ghost, y como se vio después, una porción entera sobre teología.</p>

			<p id="iw_question">UTG : Como una banda de músicos anónimos, han sido muy exitosos y han alcanzado un nivel de notoriedad y reconocimiento de la crítica que otras bandas en su género podrían envidiar, todo mientras mantienen el anonimato absoluto - ¿cómo se siente?</p>

			<p id="iw_answer">Es una experiencia especial porque estás en una banda relativamente bien conocida que viaja a todas partes, pero en la que se ve muy poco de los “resultados” habituales de la misma, a falta de un término mejor, y creo que es abrumadoramente algo positivo. Permite una muy buena manera de ver el mundo , y mantiene la experiencia muy sobria y clara, al menos en un sentido filosófico de todos modos, ya que todas las interacciones con la gente fuera de la banda son como serían para cualquier otro turista desconocido y las reacciones de la gente y las interacciones con uno a nivel personal no se ven influidas por el conocimiento que ellos tengan de que soy músico, o cómo hemos sido percibidos por la prensa, sino simplemente por lo que está ocurriendo en el momento. Creo que hay un montón de otras bandas en las que esa noción de la celebridad y la notoriedad y el prestigio individual pueden superar  su capacidad de participar efectivamente con su público y con el mundo, y pueden llevar a la disfunción de ellos como banda y puede crear un problema en el proceso creativo. Para nosotros, que estamos en una posición que es tanto una entidad propia y somos, al menos por ahora, todavía muy capaces de considerar nuestra creación desde el punto de vista externo, lo que creo que la mayoría de las otras bandas de un nivel similar o mayores han perdido la capacidad de hacer.</p>

			<p id="iw_question">UTG : Desde afuera, esta parece ser una experiencia artística y creativa muy holística e inmersiva que ustedes acogen y, obviamente, que viene a través de su show en vivo , que es esencialmente una re-imaginación en directo de una película de terror en el escenario. ¿Cómo han sido la reacción de la audiencia aquí en el festival Big Day Out y en sus propios conciertos en Australia hasta el momento?</p>

			<p id="iw_answer">Han reaccionado muy bien, creo. Una de las pequeñas peculiaridades es que nos ha tocado a coincidir con las dos cabezas de cartel, lo que significa que no hay una enorme cantidad de gente que no sepa de nosotros, viendo a nuestros sets. Sin embargo, en Auckland , por ejemplo , tocamos en un escenario doble, al aire libre, inmediatamente antes de Snoop Dogg, lo que significa que tocamos frente a toda la multitud de Snoop Dogg, y entonces tenía sentido , porque esas son las personas que nunca harían el esfuerzo de cruzar todo el festival a un lado del escenario más pequeño para vernos, y, de manera sorprendente, una gran parte de ellos se metió realmente muy bien y ese es el tipo de exposición que realmente se quiere como banda cuando se hace este tipo de festivales. Nuestro espacio, en este momento, es bueno porque es bastante tarde en la noche y en uno de los mejores escenarios para nuestro tipo de puesta en escena. El hecho de que nos enfrentemos con las dos cabezas de cartel significa que no hay un montón fanáticos de Pearl Jam o Snoop Dogg escuchándonos accidentalmente a nosotros, por ejemplo.
			</br></br>
			Por otro lado, una de las razones por las que tomamos este espacio en este festival fue la oportunidad de tocar shows alternativos, que no tuvimos la oportunidad de hacer la última vez que estuvimos aquí hace un año, por lo que ha sido realmente genial.</p>

			<p id="iw_question">UTG : Obviamente ha habido personas que optan por buscar activamente sus presentaciones y omiten la cabeza de cartel lo cual tiene que ser algo positivo, al menos para sus propios egos, lo cual me lleva a preguntar ¿estamos propensos a ver la recreación de la primera fila de mujeres dispuestas a hacer cualquier cosa para complacer a Papa Emeritus II esta noche ?</p>

			<p id="iw_answer">Por lo general, terminamos en estos espectáculos con una pequeña serie de mujeres insinuantes así como, probablemente, hombres también. Tenemos una gran cantidad de público - digamos que estoy muy contento de que muchas de las personas que usted probablemente esperaría ver en Pearl Jam, en realidad están apareciendo en nuestra presentación, lo que es salvaje.
			</br></br>
			Como he mencionado antes , una de las razones por las que decidimos hacer esta gira fue la oportunidad de tocar nuestros propios espectáculos y hemos observado que un montón de gente que se encontró con nosotros en el festival está llegando allí, así que en ese sentido es casi la oportunidad perfecta para nosotros como banda, ya que nuestros fans tienen la oportunidad de tener la verdadera experiencia Ghost en vivo en un lugar más pequeño, y tenemos algo de exposición añadida también. Por no hablar de que lleguemos a ver mucho de su hermoso país.</p>

			<p id="iw_question">UTG : Temáticamente el primer álbum parece concentrarse en predecir la llegada del Anticristo y el segundo parece concentrarse temáticamente en que anuncia su llegada, lo que me lleva a dos preguntas : la primera ¿es su intención reflejar su trayectoria profesional ? La segunda es, ¿qué viene después?</p>

			<p id="iw_answer">En cierto modo, es el espejo que refleja el estado de la banda y creo que en realidad podría ser aún más claro y evidente en el futuro con el tercer disco. Este (Infestissumam) es acerca de la presencia de Satanás y el Anticristo en sus diversas formas, mientras que el próximo disco será sobre la ausencia de Dios, y eso es todo lo que voy a decir por ahora, ya que hay un cuarto disco planeado, pero voy a dejar que usted absorba el próximo antes de que le estropee el que sigue. Sólo sepa que la ausencia de Dios y cómo la gente responde a eso, como especie y como individuos,  dará mucha forma a lo que está por venir.</p>

			<p id="iw_question">UTG : de manera infame ustedes se toparon con algunos problemas de censura en los EE.UU. , particularmente en los estados más conservadores, y yo realmente pensaba que la forma en que  han aprovechado esas cuestiones, al optar por grabar su álbum que anuncia la llegada del anticristo en la devota cristiana Nashville, Tennessee, fue un movimiento que invita a la reflexión muy artísticamente. ¿Cómo esas cuestiones y esa ciudad impactan el sonido del disco? ¿Ayudó eso a añadir autenticidad a la línea crítica religiosa presente en el disco?</p>

			<p id="iw_answer">En cierto modo, supongo. Es decir, que habíamos querido hacer nuestro gran álbum, comercial y vendedor y se suponía que el contenido debía ser profundamente religioso, así que imaginamos que no había mejor lugar para grabarlo que Nashville, la cuna de la música que suena muy cristiana y muy comercial [risas ].
			</br></br>
			No, en serio, sin embargo, aparte de nuestro pequeño incidente con el coro, no había realmente mucho acerca de Nashville que haya tenido un impacto negativo en el álbum. La ciudad de Nashville, no es tan, ya sabes, KKK, como el resto del estado. Tocamos dos conciertos en Knoxville , por ejemplo, que es increíble. Por cada lugar que vas,  a pesar de que los estados y los alrededores puedan ser conservadores, siempre hay una comunidad artística, bohemia, en el centro urbano que es exactamente lo contrario y es de izquierda de verdad y muy abierto de mente y fresco , y, obviamente, en Nashville existe una gran cantidad de músicos y traen con ellos una amplia gama de producciones creativas, puntos de vista y experiencias, y fue eso tanto como los aspectos conservadores, los que influyeron en la grabación, y creo que eso sería cierto sobre cualquier ciudad a la que fueras en todo el mundo con una comunidad artística.</p>

			<p id="iw_question">UTG : En cuanto al contenido de las letras de Infestissumam, una canción que se destacó para mí fue “Body and Blood”. Como una persona que fue criada dentro de la fe católica, la corriente subterránea de canibalismo presente en la celebración de la Eucaristía siempre parecía estar más bien intrínsecamente desordenada. Lo que me lleva a preguntarme si ¿la crítica de la religión linear contemporánea es más el punto de la banda teológicamente que la glorificación real del satanismo?</p>

			<p id="iw_answer">Creo que la glorificación de Satanás y todo lo que es oscuro está presente desde algo más que una preferencia por ese tipo de estética; artísticamente hablando eso es lo que nos habla a nosotros como individuos y como grupo.
			</br></br>
			En cuanto al aspecto lírico de la banda, es definitivamente una crítica a la religión, y la idea de las personas que optan por el comercio de sus derechos en la creencia de supuestas verdades y esencialmente desperdician sus vidas siguiendo ciegamente lo que son, esencialmente, sólo historias que la gente inventó debido a la necesidad de controlar las acciones de otros. Personalmente, y como banda, encontramos que es un fenómeno interesante y es un tema tan amplio que no nos es posible cubrir todo en el espacio de un álbum o incluso en una carrera. Así que nos centramos en y estamos inspirados por el cristianismo, o al menos el cristianismo como lo fue en el pasado de todos modos - , obviamente, algunos sectores de la cristiandad han evolucionado y cambiado con los tiempos por necesidad, como los viejos sistemas dejaron de apelar a sus propios creyentes, pero es un cambio realizado, en su mayor parte, por el deseo de mantener el control.
			</br></br>
			El cristianismo en sí mismo fue creado para controlar el flujo del movimiento cristiano oculto, por eso se crearon las iglesias, y los rituales y las formalidades. Hoy en día es una religión que se puede manipular para apaciguar y complacer a la audiencia a la que está tratando de controlar en sus opiniones.</p>

			<p id="iw_question">UTG : Su encantadora publicista me avisa que es hora de terminar, así que voy a dejarlo ir y se aliste para tocar y glorificar el satanismo, el libre pensamiento, y la teología crítica y voy a ir a buscarme un lugar privilegiado frente al escenario para participar en el ritual. Me encanta su Grucifix!</p>

			<p id="iw_answer">Gracias por tomarse el tiempo para hablar con nosotros, nos vemos más tarde para nuestro espectáculo.
			</br></br>
			Menos de una hora después de que esta entrevista tuviera lugar, tuve la suerte de encontrarme frente y al centro para la presentación de Ghost. Lo que siguió es quizá mejor descrito como una masa demoníaca. Cuando Papa Emeritus II habló con la gracia de un pontífice entre canciones, la gente respondió muy parecido a los católicos en el Vaticano, y cuando empezó la música, los movimientos de los Ghouls sin nombre y las acciones de la multitud, junto con la naturaleza oscura de la música, la iluminación, el humo y los trajes detallados crearon la sensación de que  estaba en medio de la celebración de un ritual. Un ritual que glorificaba no sólo el satanismo, el libre de pensamiento y la promiscuidad sexual, sino también la verdadera expresión artística. Mientras me alejaba del escenario me sentí como si hubiera experimentado algo completamente único, y sin duda es el mejor cumplido que uno puede hacerle a cualquier artista. Tal vez es como Rocky Erickson cantaba hace tantos años… <i>"If you have Ghost then you have everything”</i></p>

			(Fuente: <a href="http://www.underthegunreview.net/2014/02/04/utg-interview-ghost-conversation-with-a-nameless-ghoul/">underthegunreview.net</a>)
		</div>
	</div>
<html>